services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5556:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - 8082:8081
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/testdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
networks:
  backend:
    name: javadb
volumes:
  pgdata: